
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: idam-wildcard
  namespace: bseg-forgerock-dev
spec:
  secretName: idam-wildcard-tls
  issuerRef:
    name: tpp-venafi-issuer
  commonName: darkedges.com
  dnsNames:
  - "*.darkedges.com"